import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.subscriptionPlan.deleteMany({});

  await prisma.subscriptionPlan.createMany({
    data: [
      {
        name: "Free Trial",
        slug: "free-trial",
        description: "14 Days Free Trial",
        price: 0,
        durationInDays: 14,
        currency: "INR",
        maxStudents: 100,
        maxTeachers: 10,
        maxAdmins: 1,
        maxStorageInGB: 2,
        features: [
          "Student Management",
          "Teacher Management",
          "Basic Reports",
        ],
        isTrial: true,
        isPopular: false,
        isActive: true,
      },
      {
        name: "Starter Monthly",
        slug: "starter-monthly",
        description: "Small Schools & Coaching",
        price: 999,
        durationInDays: 30,
        currency: "INR",
        maxStudents: 300,
        maxTeachers: 20,
        maxAdmins: 2,
        maxStorageInGB: 5,
        features: ["Admissions", "Attendance", "Fee Management"],
        isActive: true,
      },
      {
        name: "Starter Yearly",
        slug: "starter-yearly",
        description: "Starter Annual Plan",
        price: 9999,
        durationInDays: 365,
        currency: "INR",
        maxStudents: 300,
        maxTeachers: 20,
        maxAdmins: 2,
        maxStorageInGB: 5,
        features: [
          "Admissions",
          "Attendance",
          "Fee Management",
          "Reports",
        ],
        isActive: true,
      },
      {
        name: "Growth Monthly",
        slug: "growth-monthly",
        description: "Growing Institutions",
        price: 2499,
        durationInDays: 30,
        currency: "INR",
        maxStudents: 1000,
        maxTeachers: 75,
        maxAdmins: 5,
        maxStorageInGB: 20,
        features: [
          "Student Portal",
          "Teacher Portal",
          "SMS Alerts",
          "Reports",
        ],
        isPopular: true,
        isActive: true,
      },
      {
        name: "Growth Yearly",
        slug: "growth-yearly",
        description: "Annual Growth Plan",
        price: 24999,
        durationInDays: 365,
        currency: "INR",
        maxStudents: 1000,
        maxTeachers: 75,
        maxAdmins: 5,
        maxStorageInGB: 20,
        features: [
          "Student Portal",
          "Teacher Portal",
          "SMS Alerts",
          "Reports",
        ],
        isPopular: true,
        isActive: true,
      },
      {
        name: "Professional Monthly",
        slug: "professional-monthly",
        description: "College ERP Professional",
        price: 4999,
        durationInDays: 30,
        currency: "INR",
        maxStudents: 3000,
        maxTeachers: 200,
        maxAdmins: 10,
        maxStorageInGB: 50,
        features: [
          "Timetable",
          "Examination",
          "Library",
          "Transport",
        ],
        isActive: true,
      },
      {
        name: "Professional Yearly",
        slug: "professional-yearly",
        description: "Professional Annual",
        price: 49999,
        durationInDays: 365,
        currency: "INR",
        maxStudents: 3000,
        maxTeachers: 200,
        maxAdmins: 10,
        maxStorageInGB: 50,
        features: [
          "Timetable",
          "Examination",
          "Library",
          "Transport",
        ],
        isActive: true,
      },
      {
        name: "Enterprise Monthly",
        slug: "enterprise-monthly",
        description: "Large Universities",
        price: 9999,
        durationInDays: 30,
        currency: "INR",
        maxStudents: 10000,
        maxTeachers: 1000,
        maxAdmins: 25,
        maxStorageInGB: 200,
        features: [
          "API Access",
          "Custom Branding",
          "Advanced Analytics",
          "Priority Support",
        ],
        isActive: true,
      },
      {
        name: "Enterprise Yearly",
        slug: "enterprise-yearly",
        description: "Enterprise Annual",
        price: 99999,
        durationInDays: 365,
        currency: "INR",
        maxStudents: 10000,
        maxTeachers: 1000,
        maxAdmins: 25,
        maxStorageInGB: 200,
        features: [
          "API Access",
          "Custom Branding",
          "Advanced Analytics",
          "Priority Support",
        ],
        isActive: true,
      },
      {
        name: "Unlimited Lifetime",
        slug: "unlimited-lifetime",
        description: "One Time Lifetime License",
        price: 499999,
        durationInDays: 3650,
        currency: "INR",
        maxStudents: 999999,
        maxTeachers: 999999,
        maxAdmins: 999,
        maxStorageInGB: 1000,
        features: [
          "Unlimited Students",
          "Unlimited Teachers",
          "Lifetime Updates",
          "Dedicated Support",
        ],
        isPopular: true,
        isActive: true,
      },
    ],
  });

  console.log("✅ 10 Subscription Plans Seeded Successfully");
}

main()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
  });