// Run: cd yn-udp/server && npx ts-node src/seed-templates.ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const templates = [
  {
    "name": "Professional Blue ID",
    "type": "id-card",
    "pageWidth": 382,
    "pageHeight": 550,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {
          "id": "e1",
          "type": "rect",
          "x": 0,
          "y": 0,
          "width": 382,
          "height": 550,
          "fill": "#ffffff",
          "stroke": "#1e40af",
          "strokeWidth": 3,
          "rotation": 0,
          "opacity": 1,
          "borderRadius": 8
        },
        {
          "id": "e2",
          "type": "rect",
          "x": 0,
          "y": 0,
          "width": 382,
          "height": 110,
          "fill": "#1e3a5f",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1,
          "borderRadius": 0
        },
        {
          "id": "e3",
          "type": "field",
          "x": 10,
          "y": 15,
          "width": 362,
          "height": 28,
          "text": "{{school_name}}",
          "fontSize": 16,
          "fontWeight": "bold",
          "color": "#ffffff",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e4",
          "type": "field",
          "x": 10,
          "y": 45,
          "width": 362,
          "height": 18,
          "text": "{{school_address}}",
          "fontSize": 9,
          "color": "#ffffffcc",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e5",
          "type": "text",
          "x": 10,
          "y": 70,
          "width": 362,
          "height": 20,
          "text": "STUDENT IDENTITY CARD",
          "fontSize": 11,
          "fontWeight": "bold",
          "color": "#ffffff",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e6",
          "type": "rect",
          "x": 151,
          "y": 125,
          "width": 80,
          "height": 95,
          "fill": "#f3f4f6",
          "stroke": "#1e40af",
          "strokeWidth": 2,
          "borderRadius": 4,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e7",
          "type": "text",
          "x": 161,
          "y": 160,
          "width": 60,
          "height": 20,
          "text": "PHOTO",
          "fontSize": 10,
          "color": "#9ca3af",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e8",
          "type": "field",
          "x": 20,
          "y": 240,
          "width": 342,
          "height": 22,
          "text": "{{student_name}}",
          "fontSize": 15,
          "fontWeight": "bold",
          "color": "#1e3a5f",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e9",
          "type": "field",
          "x": 20,
          "y": 270,
          "width": 342,
          "height": 18,
          "text": "Class: {{class_name}} | Sec: {{section_name}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e10",
          "type": "field",
          "x": 20,
          "y": 295,
          "width": 342,
          "height": 18,
          "text": "Roll No: {{roll_number}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e11",
          "type": "field",
          "x": 20,
          "y": 320,
          "width": 342,
          "height": 18,
          "text": "Adm No: {{admission_no}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e12",
          "type": "field",
          "x": 20,
          "y": 345,
          "width": 342,
          "height": 18,
          "text": "Father: {{father_name}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e13",
          "type": "field",
          "x": 20,
          "y": 370,
          "width": 342,
          "height": 18,
          "text": "DOB: {{dob}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e14",
          "type": "rect",
          "x": 0,
          "y": 520,
          "width": 382,
          "height": 30,
          "fill": "#1e3a5f",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e15",
          "type": "field",
          "x": 10,
          "y": 525,
          "width": 362,
          "height": 15,
          "text": "{{school_phone}} | {{school_email}}",
          "fontSize": 8,
          "color": "#ffffffcc",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        }
      ],
      "pageBg": "#ffffff"
    }
  },
  {
    "name": "Modern Green ID",
    "type": "id-card",
    "pageWidth": 382,
    "pageHeight": 550,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {
          "id": "e1",
          "type": "rect",
          "x": 0,
          "y": 0,
          "width": 382,
          "height": 550,
          "fill": "#ffffff",
          "stroke": "#059669",
          "strokeWidth": 3,
          "rotation": 0,
          "opacity": 1,
          "borderRadius": 10
        },
        {
          "id": "e2",
          "type": "rect",
          "x": 0,
          "y": 0,
          "width": 382,
          "height": 100,
          "fill": "#064e3b",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e3",
          "type": "field",
          "x": 10,
          "y": 12,
          "width": 362,
          "height": 26,
          "text": "{{school_name}}",
          "fontSize": 15,
          "fontWeight": "bold",
          "color": "#ffffff",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e4",
          "type": "field",
          "x": 10,
          "y": 40,
          "width": 362,
          "height": 16,
          "text": "{{school_address}}",
          "fontSize": 9,
          "color": "#ffffffbb",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e5",
          "type": "text",
          "x": 10,
          "y": 65,
          "width": 362,
          "height": 20,
          "text": "STUDENT ID CARD",
          "fontSize": 10,
          "fontWeight": "bold",
          "color": "#10b981",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e6",
          "type": "circle",
          "x": 156,
          "y": 115,
          "width": 70,
          "height": 70,
          "fill": "#ecfdf5",
          "stroke": "#059669",
          "strokeWidth": 2,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e7",
          "type": "field",
          "x": 20,
          "y": 205,
          "width": 342,
          "height": 22,
          "text": "{{student_name}}",
          "fontSize": 15,
          "fontWeight": "bold",
          "color": "#064e3b",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e8",
          "type": "field",
          "x": 20,
          "y": 235,
          "width": 342,
          "height": 16,
          "text": "Class: {{class_name}} | Section: {{section_name}}",
          "fontSize": 10,
          "color": "#374151",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e9",
          "type": "field",
          "x": 20,
          "y": 258,
          "width": 342,
          "height": 16,
          "text": "Roll: {{roll_number}} | Adm: {{admission_no}}",
          "fontSize": 10,
          "color": "#374151",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e10",
          "type": "field",
          "x": 20,
          "y": 281,
          "width": 342,
          "height": 16,
          "text": "Father: {{father_name}}",
          "fontSize": 10,
          "color": "#374151",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e11",
          "type": "rect",
          "x": 0,
          "y": 520,
          "width": 382,
          "height": 30,
          "fill": "#064e3b",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e12",
          "type": "field",
          "x": 10,
          "y": 525,
          "width": 362,
          "height": 15,
          "text": "{{school_phone}}",
          "fontSize": 8,
          "color": "#ffffffcc",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        }
      ],
      "pageBg": "#ffffff"
    }
  },
  {
    "name": "Royal Purple ID",
    "type": "id-card",
    "pageWidth": 382,
    "pageHeight": 550,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {
          "id": "e1",
          "type": "rect",
          "x": 0,
          "y": 0,
          "width": 382,
          "height": 120,
          "fill": "#5b21b6",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e2",
          "type": "field",
          "x": 10,
          "y": 15,
          "width": 362,
          "height": 26,
          "text": "{{school_name}}",
          "fontSize": 15,
          "fontWeight": "bold",
          "color": "#ffffff",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e3",
          "type": "field",
          "x": 10,
          "y": 42,
          "width": 362,
          "height": 16,
          "text": "{{school_address}}",
          "fontSize": 9,
          "color": "#ffffffbb",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e4",
          "type": "text",
          "x": 10,
          "y": 68,
          "width": 362,
          "height": 18,
          "text": "STUDENT IDENTITY CARD",
          "fontSize": 10,
          "fontWeight": "bold",
          "color": "#ffffff",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e5",
          "type": "text",
          "x": 100,
          "y": 92,
          "width": 182,
          "height": 16,
          "text": "Session: {{academic_year}}",
          "fontSize": 9,
          "color": "#e9d5ff",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e6",
          "type": "rect",
          "x": 151,
          "y": 135,
          "width": 80,
          "height": 95,
          "fill": "#f5f3ff",
          "stroke": "#7c3aed",
          "strokeWidth": 2,
          "borderRadius": 6,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e7",
          "type": "field",
          "x": 20,
          "y": 250,
          "width": 342,
          "height": 22,
          "text": "{{student_name}}",
          "fontSize": 15,
          "fontWeight": "bold",
          "color": "#5b21b6",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e8",
          "type": "field",
          "x": 20,
          "y": 280,
          "width": 342,
          "height": 16,
          "text": "Class: {{class_name}} | Section: {{section_name}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e9",
          "type": "field",
          "x": 20,
          "y": 303,
          "width": 342,
          "height": 16,
          "text": "Roll No: {{roll_number}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e10",
          "type": "field",
          "x": 20,
          "y": 326,
          "width": 342,
          "height": 16,
          "text": "Admission: {{admission_no}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e11",
          "type": "field",
          "x": 20,
          "y": 349,
          "width": 342,
          "height": 16,
          "text": "Father: {{father_name}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e12",
          "type": "field",
          "x": 20,
          "y": 372,
          "width": 342,
          "height": 16,
          "text": "DOB: {{dob}} | Blood: {{blood_group}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e13",
          "type": "rect",
          "x": 0,
          "y": 520,
          "width": 382,
          "height": 30,
          "fill": "#5b21b6",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e14",
          "type": "field",
          "x": 10,
          "y": 525,
          "width": 362,
          "height": 15,
          "text": "{{school_phone}} | {{school_email}}",
          "fontSize": 8,
          "color": "#ffffffcc",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        }
      ],
      "pageBg": "#ffffff"
    }
  },
  {
    "name": "Classic Gold ID",
    "type": "id-card",
    "pageWidth": 382,
    "pageHeight": 550,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {
          "id": "e1",
          "type": "rect",
          "x": 5,
          "y": 5,
          "width": 372,
          "height": 540,
          "fill": "transparent",
          "stroke": "#92400e",
          "strokeWidth": 3,
          "borderRadius": 6,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e2",
          "type": "rect",
          "x": 0,
          "y": 0,
          "width": 382,
          "height": 105,
          "fill": "#78350f",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e3",
          "type": "field",
          "x": 10,
          "y": 12,
          "width": 362,
          "height": 26,
          "text": "{{school_name}}",
          "fontSize": 15,
          "fontWeight": "bold",
          "color": "#fbbf24",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e4",
          "type": "field",
          "x": 10,
          "y": 40,
          "width": 362,
          "height": 16,
          "text": "{{school_address}}",
          "fontSize": 9,
          "color": "#fde68a",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e5",
          "type": "text",
          "x": 10,
          "y": 65,
          "width": 362,
          "height": 18,
          "text": "STUDENT ID CARD",
          "fontSize": 11,
          "fontWeight": "bold",
          "color": "#ffffff",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e6",
          "type": "rect",
          "x": 151,
          "y": 120,
          "width": 80,
          "height": 95,
          "fill": "#fffbeb",
          "stroke": "#b45309",
          "strokeWidth": 2,
          "borderRadius": 4,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e7",
          "type": "field",
          "x": 20,
          "y": 235,
          "width": 342,
          "height": 22,
          "text": "{{student_name}}",
          "fontSize": 15,
          "fontWeight": "bold",
          "color": "#78350f",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e8",
          "type": "field",
          "x": 20,
          "y": 265,
          "width": 342,
          "height": 16,
          "text": "Class: {{class_name}} | Section: {{section_name}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e9",
          "type": "field",
          "x": 20,
          "y": 288,
          "width": 342,
          "height": 16,
          "text": "Roll No: {{roll_number}} | Adm: {{admission_no}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e10",
          "type": "field",
          "x": 20,
          "y": 311,
          "width": 342,
          "height": 16,
          "text": "Father: {{father_name}}",
          "fontSize": 10,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e11",
          "type": "rect",
          "x": 0,
          "y": 520,
          "width": 382,
          "height": 30,
          "fill": "#78350f",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e12",
          "type": "field",
          "x": 10,
          "y": 525,
          "width": 362,
          "height": 15,
          "text": "{{school_phone}}",
          "fontSize": 8,
          "color": "#fde68a",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        }
      ],
      "pageBg": "#ffffff"
    }
  },
  {
    "name": "Minimalist Red ID",
    "type": "id-card",
    "pageWidth": 382,
    "pageHeight": 550,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {
          "id": "e1",
          "type": "rect",
          "x": 0,
          "y": 0,
          "width": 382,
          "height": 8,
          "fill": "#dc2626",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e2",
          "type": "field",
          "x": 20,
          "y": 25,
          "width": 342,
          "height": 24,
          "text": "{{school_name}}",
          "fontSize": 14,
          "fontWeight": "bold",
          "color": "#dc2626",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e3",
          "type": "field",
          "x": 20,
          "y": 50,
          "width": 342,
          "height": 14,
          "text": "{{school_address}}",
          "fontSize": 8,
          "color": "#6b7280",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e4",
          "type": "line",
          "x": 40,
          "y": 72,
          "width": 302,
          "height": 2,
          "stroke": "#fca5a5",
          "strokeWidth": 1,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e5",
          "type": "rect",
          "x": 156,
          "y": 90,
          "width": 70,
          "height": 85,
          "fill": "#fef2f2",
          "stroke": "#dc2626",
          "strokeWidth": 1,
          "borderRadius": 4,
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e6",
          "type": "field",
          "x": 20,
          "y": 195,
          "width": 342,
          "height": 22,
          "text": "{{student_name}}",
          "fontSize": 15,
          "fontWeight": "bold",
          "color": "#111827",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e7",
          "type": "field",
          "x": 20,
          "y": 225,
          "width": 342,
          "height": 16,
          "text": "Class: {{class_name}} | Section: {{section_name}}",
          "fontSize": 10,
          "color": "#6b7280",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e8",
          "type": "field",
          "x": 20,
          "y": 248,
          "width": 342,
          "height": 16,
          "text": "Roll: {{roll_number}} | Adm: {{admission_no}}",
          "fontSize": 10,
          "color": "#6b7280",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e9",
          "type": "field",
          "x": 20,
          "y": 271,
          "width": 342,
          "height": 16,
          "text": "Father: {{father_name}}",
          "fontSize": 10,
          "color": "#6b7280",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e10",
          "type": "rect",
          "x": 0,
          "y": 542,
          "width": 382,
          "height": 8,
          "fill": "#dc2626",
          "stroke": "transparent",
          "strokeWidth": 0,
          "rotation": 0,
          "opacity": 1
        }
      ],
      "pageBg": "#ffffff"
    }
  },
  {
    "name": "Achievement Certificate",
    "type": "certificate",
    "pageWidth": 794,
    "pageHeight": 1123,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {
          "id": "e1",
          "type": "rect",
          "x": 20,
          "y": 20,
          "width": 754,
          "height": 1083,
          "stroke": "#1e40af",
          "strokeWidth": 4,
          "fill": "transparent",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e2",
          "type": "rect",
          "x": 35,
          "y": 35,
          "width": 724,
          "height": 1053,
          "stroke": "#1e40af",
          "strokeWidth": 1,
          "fill": "transparent",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e3",
          "type": "field",
          "x": 150,
          "y": 80,
          "width": 494,
          "height": 40,
          "text": "{{school_name}}",
          "fontSize": 28,
          "fontWeight": "bold",
          "color": "#1e3a5f",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e4",
          "type": "field",
          "x": 150,
          "y": 130,
          "width": 494,
          "height": 20,
          "text": "{{school_address}}",
          "fontSize": 12,
          "color": "#6b7280",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e5",
          "type": "text",
          "x": 150,
          "y": 220,
          "width": 494,
          "height": 50,
          "text": "CERTIFICATE OF ACHIEVEMENT",
          "fontSize": 36,
          "fontWeight": "bold",
          "color": "#1e40af",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e6",
          "type": "text",
          "x": 150,
          "y": 320,
          "width": 494,
          "height": 25,
          "text": "This is to certify that",
          "fontSize": 16,
          "color": "#374151",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e7",
          "type": "field",
          "x": 150,
          "y": 370,
          "width": 494,
          "height": 40,
          "text": "{{student_name}}",
          "fontSize": 30,
          "fontWeight": "bold",
          "color": "#1e3a5f",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e8",
          "type": "field",
          "x": 150,
          "y": 430,
          "width": 494,
          "height": 25,
          "text": "of Class {{class_name}} - Section {{section_name}}",
          "fontSize": 16,
          "color": "#374151",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e9",
          "type": "text",
          "x": 100,
          "y": 490,
          "width": 594,
          "height": 50,
          "text": "has successfully completed the academic year with distinction and excellence.",
          "fontSize": 15,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e10",
          "type": "field",
          "x": 60,
          "y": 950,
          "width": 200,
          "height": 20,
          "text": "Date: {{current_date}}",
          "fontSize": 12,
          "color": "#374151",
          "textAlign": "left",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e11",
          "type": "text",
          "x": 530,
          "y": 950,
          "width": 200,
          "height": 20,
          "text": "Principal",
          "fontSize": 12,
          "color": "#374151",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e12",
          "type": "line",
          "x": 530,
          "y": 945,
          "width": 180,
          "height": 2,
          "stroke": "#374151",
          "strokeWidth": 1,
          "rotation": 0,
          "opacity": 1
        }
      ],
      "pageBg": "#ffffff"
    }
  },
  {
    "name": "Character Certificate",
    "type": "certificate",
    "pageWidth": 794,
    "pageHeight": 1123,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {
          "id": "e1",
          "type": "rect",
          "x": 15,
          "y": 15,
          "width": 764,
          "height": 1093,
          "stroke": "#92400e",
          "strokeWidth": 4,
          "fill": "transparent",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e2",
          "type": "rect",
          "x": 28,
          "y": 28,
          "width": 738,
          "height": 1067,
          "stroke": "#b45309",
          "strokeWidth": 1,
          "fill": "transparent",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e3",
          "type": "field",
          "x": 150,
          "y": 80,
          "width": 494,
          "height": 36,
          "text": "{{school_name}}",
          "fontSize": 26,
          "fontWeight": "bold",
          "color": "#78350f",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e4",
          "type": "field",
          "x": 150,
          "y": 125,
          "width": 494,
          "height": 20,
          "text": "{{school_address}}",
          "fontSize": 12,
          "color": "#92400e",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e5",
          "type": "text",
          "x": 200,
          "y": 200,
          "width": 394,
          "height": 45,
          "text": "CHARACTER CERTIFICATE",
          "fontSize": 32,
          "fontWeight": "bold",
          "color": "#92400e",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e6",
          "type": "text",
          "x": 80,
          "y": 300,
          "width": 634,
          "height": 25,
          "text": "This is to certify that",
          "fontSize": 16,
          "color": "#374151",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e7",
          "type": "field",
          "x": 150,
          "y": 345,
          "width": 494,
          "height": 40,
          "text": "{{student_name}}",
          "fontSize": 28,
          "fontWeight": "bold",
          "color": "#78350f",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e8",
          "type": "text",
          "x": 80,
          "y": 420,
          "width": 634,
          "height": 80,
          "text": "is a student of good moral character. During the period of study, the conduct and character was found to be satisfactory.",
          "fontSize": 15,
          "color": "#4b5563",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        },
        {
          "id": "e9",
          "type": "text",
          "x": 530,
          "y": 950,
          "width": 200,
          "height": 20,
          "text": "Principal",
          "fontSize": 12,
          "color": "#374151",
          "textAlign": "center",
          "rotation": 0,
          "opacity": 1
        }
      ],
      "pageBg": "#ffffff"
    }
  }
,
  {
    "name": "Classic Report Card",
    "type": "report-card",
    "pageWidth": 794,
    "pageHeight": 1123,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {"id":"rc1","type":"rect","x":0,"y":0,"width":794,"height":1123,"fill":"#ffffff","stroke":"#1e3a5f","strokeWidth":4,"rotation":0,"opacity":1,"borderRadius":0},
        {"id":"rc2","type":"rect","x":15,"y":15,"width":764,"height":1093,"fill":"transparent","stroke":"#1e3a5f","strokeWidth":1,"rotation":0,"opacity":1,"borderRadius":0},
        {"id":"rc3","type":"field","x":50,"y":30,"width":694,"height":36,"text":"{{school_name}}","fontSize":24,"fontWeight":"bold","color":"#1e3a5f","textAlign":"center","rotation":0,"opacity":1},
        {"id":"rc4","type":"field","x":50,"y":70,"width":694,"height":22,"text":"{{school_address}}","fontSize":14,"fontWeight":"normal","color":"#555555","textAlign":"center","rotation":0,"opacity":1},
        {"id":"rc5","type":"text","x":250,"y":110,"width":294,"height":32,"text":"REPORT CARD","fontSize":22,"fontWeight":"bold","color":"#1e3a5f","textAlign":"center","rotation":0,"opacity":1},
        {"id":"rc6","type":"text","x":50,"y":160,"width":200,"height":20,"text":"Academic Year:","fontSize":12,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc7","type":"field","x":180,"y":160,"width":200,"height":20,"text":"{{academic_year}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc8","type":"text","x":50,"y":190,"width":200,"height":20,"text":"Student Name:","fontSize":12,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc9","type":"field","x":180,"y":190,"width":300,"height":20,"text":"{{student_name}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc10","type":"text","x":50,"y":220,"width":200,"height":20,"text":"Class & Section:","fontSize":12,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc11","type":"field","x":180,"y":220,"width":200,"height":20,"text":"{{class_name}} - {{section_name}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc12","type":"text","x":450,"y":190,"width":200,"height":20,"text":"Admission No:","fontSize":12,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc13","type":"field","x":560,"y":190,"width":180,"height":20,"text":"{{admission_no}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc14","type":"text","x":450,"y":220,"width":200,"height":20,"text":"Roll No:","fontSize":12,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc15","type":"field","x":560,"y":220,"width":100,"height":20,"text":"{{roll_no}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc16","type":"text","x":50,"y":270,"width":694,"height":24,"text":"EXAMINATION RESULTS","fontSize":14,"fontWeight":"bold","color":"#ffffff","textAlign":"center","rotation":0,"opacity":1,"fill":"#1e3a5f"},
        {"id":"rc17","type":"rect","x":50,"y":265,"width":694,"height":28,"fill":"#1e3a5f","stroke":"transparent","strokeWidth":0,"rotation":0,"opacity":1,"borderRadius":4},
        {"id":"rc18","type":"field","x":50,"y":310,"width":694,"height":400,"text":"{{marks_table}}","fontSize":11,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc19","type":"text","x":50,"y":750,"width":200,"height":20,"text":"Total Marks:","fontSize":13,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc20","type":"field","x":180,"y":750,"width":150,"height":20,"text":"{{total_marks}}","fontSize":13,"fontWeight":"bold","color":"#1e3a5f","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc21","type":"text","x":350,"y":750,"width":100,"height":20,"text":"Percentage:","fontSize":13,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc22","type":"field","x":460,"y":750,"width":100,"height":20,"text":"{{percentage}}%","fontSize":13,"fontWeight":"bold","color":"#1e3a5f","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc23","type":"text","x":570,"y":750,"width":80,"height":20,"text":"Grade:","fontSize":13,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc24","type":"field","x":630,"y":750,"width":80,"height":20,"text":"{{grade}}","fontSize":13,"fontWeight":"bold","color":"#16a34a","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc25","type":"text","x":50,"y":790,"width":200,"height":20,"text":"Result:","fontSize":13,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc26","type":"field","x":120,"y":790,"width":100,"height":20,"text":"{{status}}","fontSize":13,"fontWeight":"bold","color":"#16a34a","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc27","type":"text","x":50,"y":850,"width":200,"height":20,"text":"Remarks:","fontSize":12,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc28","type":"field","x":130,"y":850,"width":400,"height":20,"text":"{{remarks}}","fontSize":12,"fontWeight":"normal","color":"#555555","textAlign":"left","rotation":0,"opacity":1},
        {"id":"rc29","type":"text","x":50,"y":1000,"width":200,"height":16,"text":"Class Teacher","fontSize":11,"fontWeight":"normal","color":"#555555","textAlign":"center","rotation":0,"opacity":1},
        {"id":"rc30","type":"text","x":300,"y":1000,"width":200,"height":16,"text":"Exam Controller","fontSize":11,"fontWeight":"normal","color":"#555555","textAlign":"center","rotation":0,"opacity":1},
        {"id":"rc31","type":"text","x":550,"y":1000,"width":200,"height":16,"text":"Principal","fontSize":11,"fontWeight":"normal","color":"#555555","textAlign":"center","rotation":0,"opacity":1},
        {"id":"rc32","type":"rect","x":50,"y":990,"width":150,"height":1,"fill":"#999999","stroke":"transparent","strokeWidth":0,"rotation":0,"opacity":1,"borderRadius":0},
        {"id":"rc33","type":"rect","x":320,"y":990,"width":150,"height":1,"fill":"#999999","stroke":"transparent","strokeWidth":0,"rotation":0,"opacity":1,"borderRadius":0},
        {"id":"rc34","type":"rect","x":580,"y":990,"width":150,"height":1,"fill":"#999999","stroke":"transparent","strokeWidth":0,"rotation":0,"opacity":1,"borderRadius":0}
      ],
      "pageBg": "#ffffff"
    }
  },
  {
    "name": "Modern Green Report Card",
    "type": "report-card",
    "pageWidth": 794,
    "pageHeight": 1123,
    "orientation": "portrait",
    "tenantId": "000000000000000000000000",
    "canvasJSON": {
      "elements": [
        {"id":"mg1","type":"rect","x":0,"y":0,"width":794,"height":1123,"fill":"#f0fdf4","stroke":"#166534","strokeWidth":3,"rotation":0,"opacity":1,"borderRadius":0},
        {"id":"mg2","type":"rect","x":0,"y":0,"width":794,"height":90,"fill":"#166534","stroke":"transparent","strokeWidth":0,"rotation":0,"opacity":1,"borderRadius":0},
        {"id":"mg3","type":"field","x":50,"y":20,"width":694,"height":30,"text":"{{school_name}}","fontSize":22,"fontWeight":"bold","color":"#ffffff","textAlign":"center","rotation":0,"opacity":1},
        {"id":"mg4","type":"field","x":50,"y":55,"width":694,"height":20,"text":"{{school_address}}","fontSize":12,"fontWeight":"normal","color":"#dcfce7","textAlign":"center","rotation":0,"opacity":1},
        {"id":"mg5","type":"rect","x":250,"y":100,"width":294,"height":35,"fill":"#dcfce7","stroke":"#166534","strokeWidth":1,"rotation":0,"opacity":1,"borderRadius":20},
        {"id":"mg6","type":"text","x":250,"y":107,"width":294,"height":24,"text":"PROGRESS REPORT","fontSize":16,"fontWeight":"bold","color":"#166534","textAlign":"center","rotation":0,"opacity":1},
        {"id":"mg7","type":"text","x":50,"y":160,"width":150,"height":18,"text":"Student Name:","fontSize":12,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg8","type":"field","x":170,"y":160,"width":280,"height":18,"text":"{{student_name}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg9","type":"text","x":50,"y":185,"width":150,"height":18,"text":"Class:","fontSize":12,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg10","type":"field","x":170,"y":185,"width":150,"height":18,"text":"{{class_name}} - {{section_name}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg11","type":"text","x":450,"y":160,"width":150,"height":18,"text":"Admission No:","fontSize":12,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg12","type":"field","x":570,"y":160,"width":180,"height":18,"text":"{{admission_no}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg13","type":"text","x":450,"y":185,"width":150,"height":18,"text":"Exam:","fontSize":12,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg14","type":"field","x":570,"y":185,"width":180,"height":18,"text":"{{exam_name}}","fontSize":12,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg15","type":"rect","x":50,"y":220,"width":694,"height":2,"fill":"#166534","stroke":"transparent","strokeWidth":0,"rotation":0,"opacity":0.5,"borderRadius":0},
        {"id":"mg16","type":"field","x":50,"y":240,"width":694,"height":450,"text":"{{marks_table}}","fontSize":11,"fontWeight":"normal","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg17","type":"rect","x":50,"y":720,"width":694,"height":2,"fill":"#166534","stroke":"transparent","strokeWidth":0,"rotation":0,"opacity":0.5,"borderRadius":0},
        {"id":"mg18","type":"text","x":50,"y":740,"width":150,"height":20,"text":"Total:","fontSize":14,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg19","type":"field","x":120,"y":740,"width":100,"height":20,"text":"{{total_marks}}","fontSize":14,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg20","type":"text","x":280,"y":740,"width":100,"height":20,"text":"Percentage:","fontSize":14,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg21","type":"field","x":390,"y":740,"width":80,"height":20,"text":"{{percentage}}%","fontSize":14,"fontWeight":"bold","color":"#333333","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg22","type":"text","x":500,"y":740,"width":80,"height":20,"text":"Grade:","fontSize":14,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg23","type":"field","x":560,"y":740,"width":60,"height":20,"text":"{{grade}}","fontSize":14,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg24","type":"text","x":640,"y":740,"width":80,"height":20,"text":"{{status}}","fontSize":14,"fontWeight":"bold","color":"#166534","textAlign":"left","rotation":0,"opacity":1},
        {"id":"mg25","type":"text","x":80,"y":1020,"width":150,"height":14,"text":"Class Teacher","fontSize":10,"fontWeight":"normal","color":"#555555","textAlign":"center","rotation":0,"opacity":1},
        {"id":"mg26","type":"text","x":330,"y":1020,"width":150,"height":14,"text":"Exam Coordinator","fontSize":10,"fontWeight":"normal","color":"#555555","textAlign":"center","rotation":0,"opacity":1},
        {"id":"mg27","type":"text","x":580,"y":1020,"width":150,"height":14,"text":"Principal","fontSize":10,"fontWeight":"normal","color":"#555555","textAlign":"center","rotation":0,"opacity":1}
      ],
      "pageBg": "#f0fdf4"
    }
  }
];

async function main() {
  console.log("🌱 Seeding design templates...");
  for (const tmpl of templates) {
    const existing = await prisma.designTemplate.findFirst({
      where: { name: tmpl.name, tenantId: tmpl.tenantId }
    });
    if (existing) {
      console.log(`  ⏩ "${tmpl.name}" already exists, skipping`);
      continue;
    }
    await prisma.designTemplate.create({
      data: {
        name: tmpl.name,
        type: tmpl.type,
        category: null,
        canvasJSON: tmpl.canvasJSON,
        pageWidth: tmpl.pageWidth,
        pageHeight: tmpl.pageHeight,
        orientation: tmpl.orientation,
        tenantId: tmpl.tenantId,
        thumbnail: null,
      }
    });
    console.log(`  ✅ "${tmpl.name}" (${tmpl.type}) created`);
  }
  console.log("\n✅ Done! All templates seeded.");
  await prisma.$disconnect();
}

main().catch(e => { console.error(e); process.exit(1); });
