/*export const feeReportTemplate = (data: any) => {
  const date = data?.date
    ? new Date(data.date).toLocaleString("en-IN")
    : new Date().toLocaleString("en-IN");

  const format = (num: number) =>
    new Intl.NumberFormat("en-IN").format(num || 0);

  return `
  <html>
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        padding: 20px;
        color: #333;
      }

      .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 2px solid #ddd;
        padding-bottom: 10px;
        margin-bottom: 20px;
      }

      .left {
        display: flex;
        align-items: center;
        gap: 15px;
      }

      .logo {
        height: 60px;
        width: 60px;
        object-fit: contain;
      }

      .school {
        font-size: 22px;
        font-weight: bold;
      }

      .meta {
        font-size: 12px;
        color: #555;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
      }

      th, td {
        border: 1px solid #ddd;
        padding: 10px;
        text-align: center;
      }

      th {
        background: #4CAF50;
        color: white;
      }

      tr:nth-child(even) {
        background: #f9f9f9;
      }

      tr:hover {
        background: #f1f1f1;
      }

      .summary {
        margin-top: 20px;
        font-size: 16px;
      }

      .footer {
        margin-top: 40px;
        text-align: center;
        font-size: 12px;
        color: #777;
      }
    </style>
  </head>

  <body>

    <!-- HEADER -->
    <div class="header">
      
      <div class="left">
        ${
          data?.schoolLogo
            ? `<img src="${data.schoolLogo}" class="logo" />`
            : ""
        }

        <div>
          <div class="school">${data?.schoolName || "School"}</div>
          <div><b>Fees Report</b></div>
        </div>
      </div>

      <div style="text-align:right;">
        <div class="meta">Generated by: ${
          data?.generatedBy || "Admin"
        }</div>
        <div class="meta">Date: ${date}</div>
      </div>

    </div>

    <!-- TABLE -->
    <table>
      <tr>
        <th>Class</th>
        <th>Total</th>
        <th>Paid</th>
        <th>Pending</th>
        <th>Students</th>
      </tr>

      ${
        Object.entries(data?.classReport || {})
          .map(
            ([cls, val]: any) => `
        <tr>
          <td>${cls}</td>
          <td>₹${format(val?.total)}</td>
          <td>₹${format(val?.paid)}</td>
          <td>₹${format(val?.pending)}</td>
          <td>${val?.students || 0}</td>
        </tr>`
          )
          .join("") || `
        <tr>
          <td colspan="5">No Data Available</td>
        </tr>`
      }
    </table>

    <!-- SUMMARY -->
    <div class="summary">
      <div><b>Total Collection:</b> ₹${format(
        data?.collection?.totalCollection
      )}</div>
      <div><b>Pending Amount:</b> ₹${format(
        data?.defaulters?.totalPending
      )}</div>
    </div>

    <!-- FOOTER -->
    <div class="footer">
      <hr/>
      <div>Generated on ${date}</div>
    </div>

  </body>
  </html>
  `;
};*/

export const feeReportTemplate = (data: any) => {
  const date = data?.date
    ? new Date(data.date).toLocaleString("en-IN")
    : new Date().toLocaleString("en-IN");

  const format = (num: number) =>
    new Intl.NumberFormat("en-IN").format(num || 0);

  const title = data?.title || "Fees Report";

  // 🎯 MODE DETECT
  const isStudent = data?.records; // student ledger
  const isClassFiltered = Array.isArray(data); // class filter returns array

  return `
  <html>
  <head>
    <style>
      body { font-family: Arial; padding:20px; }
      .header { display:flex; justify-content:space-between; border-bottom:2px solid #ddd; margin-bottom:20px; }
      .left { display:flex; gap:10px; align-items:center; }
      .logo { height:60px; }
      table { width:100%; border-collapse: collapse; margin-top:20px; }
      th, td { border:1px solid #ddd; padding:10px; text-align:center; }
      th { background:#4CAF50; color:white; }
      .footer { margin-top:30px; text-align:center; font-size:12px; }
    </style>
  </head>

  <body>

    <!-- HEADER -->
    <div class="header">
      <div class="left">
        ${data?.schoolLogo ? `<img src="${data.schoolLogo}" class="logo"/>` : ""}
        <div>
          <div><b>${data?.schoolName || "School"}</b></div>
          <div>${title}</div>
        </div>
      </div>

      <div>
        <div>By: ${data?.generatedBy || "Admin"}</div>
        <div>${date}</div>
      </div>
    </div>

    ${
      // 🟣 STUDENT LEDGER MODE
      isStudent
        ? `
      <table>
        <tr>
          <th>Total</th>
          <th>Paid</th>
          <th>Pending</th>
        </tr>
        <tr>
          <td>₹${format(data.total)}</td>
          <td>₹${format(data.paid)}</td>
          <td>₹${format(data.pending)}</td>
        </tr>
      </table>

      <h3>Transactions</h3>
      <table>
        <tr>
          <th>Amount</th>
          <th>Date</th>
        </tr>
        ${
          data.records
            ?.flatMap((r: any) =>
              r.payments.map(
                (p: any) => `
              <tr>
                <td>₹${format(p.amount)}</td>
                <td>${new Date(p.createdAt).toLocaleDateString("en-IN")}</td>
              </tr>
            `
              )
            )
            .join("") || "<tr><td colspan='2'>No Data</td></tr>"
        }
      </table>
    `
        : isClassFiltered
        ? `
      <!-- 🔵 CLASS FILTER MODE -->
      <table>
        <tr>
          <th>Student</th>
          <th>Total</th>
          <th>Paid</th>
          <th>Pending</th>
        </tr>
        ${
          data
            .map(
              (d: any) => `
          <tr>
            <td>${d.studentName}</td>
            <td>₹${format(d.total)}</td>
            <td>₹${format(d.paid)}</td>
            <td>₹${format(d.pending)}</td>
          </tr>
        `
            )
            .join("") || "<tr><td colspan='4'>No Data</td></tr>"
        }
      </table>
    `
        : `
      <!-- 🟢 FULL DASHBOARD MODE -->
      <table>
        <tr>
          <th>Class</th>
          <th>Total</th>
          <th>Paid</th>
          <th>Pending</th>
          <th>Students</th>
        </tr>

        ${
          Object.entries(data?.classReport || {})
            .map(
              ([cls, val]: any) => `
          <tr>
            <td>${cls}</td>
            <td>₹${format(val.total)}</td>
            <td>₹${format(val.paid)}</td>
            <td>₹${format(val.pending)}</td>
            <td>${val.students}</td>
          </tr>
        `
            )
            .join("") || "<tr><td colspan='5'>No Data</td></tr>"
        }
      </table>

      <div style="margin-top:20px;">
        <b>Total Collection:</b> ₹${format(
          data?.collection?.totalCollection
        )}<br/>
        <b>Pending Amount:</b> ₹${format(
          data?.defaulters?.totalPending
        )}
      </div>
    `
    }

    <div class="footer">
      <hr/>
      Generated on ${date}
    </div>

  </body>
  </html>
  `;
};